### ISSUE TITLE
Cannot include sibling directories via config file

### ISSUE THREAD

**Issue by chadmoone** [sleekbyte/tailor#295]
I can't seem to include parent or sibling directories in the file list when specifying via the config file.

For example, this works:
`$ tailor ../MyPod/Classes`

But this does not work in a config:
```
include:
    - '../MyPod/Classes'
```
or 
```
include:
    - ../MyPod/Classes
```
**Use case:**

For development of CocoaPods, we have adopted the directory pattern:
```
MyPod/
  MyClass.swift
MyPodExample/
  Podfile
  MyPodExample.xcodeproj
  Pods
```
This allows us to verify the pod by setting up an example project which actually imports it as a pod, and also keeps the actual pod files free from the extra weight of the example project.  This is not an uncommon pattern, and is also used by some popular pods including AFNetworking.

We would like to be able to set the Tailor build phase to run and cover these files, but I can't seem to get it to work with the config file.

We could get around this my customizing the build phase script, but it seems like this should be possible via the config.

**Comment by alykhank** [comment]
Agreed, it would be good to support matching styles from the CLI and the config file. Currently, the issue with referring to parent directories is due to Java glob not supporting the `..` construction, so we are investigating a workaround.

**Comment by adityatrivedi** [comment]
So after a thorough investigation, we have determined that it will not be possible to support both glob expansion as well as `..` in the paths in the config file. We ultimately want to prioritize glob expansion since it is something we use, and `..` does have a viable workaround (run `tailor` from the parent directory).

The root of the issue is that to support glob expansions, we start searching the directory tree from the location that `tailor` was called from, and check if the patterns in the config file match any file/directory. This results in the behaviour that you are seeing where files/dirs outside the `$PWD` are not checked. We could remedy this by starting the search from some number of directories above (or `~` or `/`), but this introduces a fragile unknown that we're not comfortable with due to potential security concerns.

**Comment by chadmoone** [comment]
Fair enough. Thanks for investigating!
