### ISSUE TITLE
Does not return valid json.

### ISSUE THREAD

**Issue by mikesive** [sleekbyte/tailor#317]
```
{
  "path": "/main.swift",
  "violations": [
    {
      "severity": "warning",
      "rule": "constant-naming",
      "location": {
        "line": 1,
        "column": 5
      },
      "message": "Global Constant should be either lowerCamelCase or UpperCamelCase"
    }
  ],
  "parsed": true
}  <------ should be a comma here
{
  "summary": {
    "violations": 1,
    "warnings": 1,
    "analyzed": 1,
    "errors": 0,
    "skipped": 0
  }
}
```

**Comment by mikesive** [comment]
There are also multiple root elements in the json object.

**Comment by alykhank** [comment]
Thank you for reporting @mikesive! In Tailor 0.5.0 the JSON format that we settled upon was to output each file's messages as a separate JSON object, and the summary independently as well (see https://github.com/sleekbyte/tailor#json-formatter). Since it appears that a "single-document style" is preferred, we will move to one root element going forward.

**Comment by mikesive** [comment]
No problem! I have forked the repo and changed the linter to return one single json array, feel free to use this if you don't want to change it yourself.
