### ISSUE TITLE
todo-syntax false positives for substrings and lowercase

### ISSUE THREAD

**Issue by joaoscalett** [sleekbyte/tailor#355]
Comments with words partially containing the word "todo" are marked the todo-syntax error, even if it is not a TODO comment.

E.g. in a comment with the word Todorov (could be a name of a method, class, variable, etc.), the issue happens, and I have to either disable tailor on the comment or misspell the word. Which are both bad, since I want to keep tailor on, while I correctly spell the word in the comment.

I suggest assuming the todo-syntax mark only if there is a TODO word that, either:
1. is NOT substring of another (like in "Todorov")
2. is the first word of the comment
3. is all in capital case.

**Comment by alykhank** [comment]
Thanks for reporting @joaoscalett! Based on the original intent of this rule, we've decided to switch to only flagging comments that contain "todo" as isolated words when they are in an incorrect format (as you've suggested). However, we will still flag instances regardless of case and location of the word because we want to encourage the "preferred syntax" when TODO tasks are mentioned later in a comment or with different capitalization.

Thanks for your suggestions, the fix is forthcoming!
