### ISSUE TITLE
[trailing-closure] rule needs to be more stringent

### ISSUE THREAD

**Issue by ArtSabintsev** [sleekbyte/tailor#401]
**Tailor Version:** v0.9.0
**Swift Version:** 2.2
**Platform (Mac/Linux/Windows/CI):** Mac
**Installation Method:** Homebrew

```
guard let x = x.filter({ return $0.id == someString }).first else {
    return
}
```
The code snippet above requires parenthesis as it is a chained call.

Unfortunately, tailor flags this as an issue requiring that a trailing-closure should be used.

Please make this rule more stringent.

**Comment by ArtSabintsev** [comment]
Also, situations like this one are improperly flagged as you need the parenthesis:

```
if y.contains({ return $0.id == someString }) {
```

**Comment by a4sriniv** [comment]
Trailing closures can be used for chained expressions, so `val first = x.filter { return $0.id == someString } .first` would work on its own. For some reason though, the parens are necessary inside condition clauses (in `if`, `while`, `guard` statements) and the code doesn't compile otherwise. This isn't documented at all anywhere, so I was wondering if you know of any other constructs where you've noticed the parens are necessary?

For now, I'm going to disable this check inside condition clauses.

**Comment by ArtSabintsev** [comment]
Can't think of any other situations at the moment.

Thanks!
