### ISSUE TITLE
VariableNameContext Never Populated

### ISSUE THREAD

**Issue by esheri3** [sleekbyte/tailor#422]
**Tailor Version:** v0.1.0

**Swift Version:** 2.0

**Platform (Mac/Linux/Windows/CI):** Mac

**Installation Method:** Git clone

### General

I am attempting to utilize Tailor capabilities programmatically rather then call Tailor via CLI. Particularly interested in the well formedness of the generated AST.

### Steps to Reproduce Issue

1. Parse the AST using one of the sample test files in the git repo (ex: functions.swift)
2. Walk the AST using the ParseTreeWalker

```
for(TopLevelContext topLevel : topLevels) {
        ParseTreeWalker walker = new ParseTreeWalker();
        walker.walk(new SwiftBaseListener() {
            @Override
            public void enterVariableName(SwiftParser.VariableNameContext ctx) {
                System.err.println("!!! VAR: " + ctx.getText());
                super.enterVariableName(ctx);
            }
        }, topLevel);
}
```

### Expected Behavior

I would expect the enterVariableName method to be called and thus I would expect the variable names to printed to sterr

### Actual Behavior

Nothing is printed as the method is never called. If you override enterVariableDeclaration (or visitVariableDeclaration if using Visitor), the variableDeclarationContext.variableName() method returns null. variableDeclarationContext.getText() returns something like "varsomething:String". It does not appear the VariableNameContext is getting populated correctly which impacts the ability to do checks on local variable names.

**Comment by a4sriniv** [comment]
Hey @esheri3, sorry for the late reply! Almost all variable declarations use the `patternInitializer` form of variable declarations:  `variableDeclaration: variableDeclarationHead patternInitializerList`.
This does not contain `variableName` as part of the rule. Only variable declarations with `get`/`set` clauses or `willSet`/`didSet` clauses will match with the rules that contain `variableName`, which is why `VariableNameContext` is never getting populated.

If you want to extract variable names from `PatternInitializerContext`, I'd recommend taking a look at [this](https://github.com/sleekbyte/tailor/blob/master/src/main/java/com/sleekbyte/tailor/listeners/DeclarationListener.java#L96).
